### ISSUE TITLE
Error on @mux - 'hls.js' does not contain a default export (imported as 'ue').

### ISSUE THREAD

**Issue by Rychillie** [muxinc/next-video#109] opened 2023-11-13 01:58 UTC
I did a simple installation and run the project...

Error:
```
./node_modules/@mux/playback-core/dist/index.mjs
Attempted import error: 'hls.js' does not contain a default export (imported as 'ue').

Import trace for requested module:
./node_modules/@mux/playback-core/dist/index.mjs
./node_modules/@mux/mux-player-react/dist/index.mjs
./node_modules/next-video/dist/components/default-player.js
./node_modules/next-video/dist/components/video.js
```

**Comment by andrewjl-mux** [comment] 2023-11-13 21:15
Thank you for filing this issue! We are investigating the root cause in tandem with https://github.com/muxinc/elements/issues/818.

**Comment by lpbonomi** [comment] 2023-11-16 10:29
This looks like a bug from Next.js https://github.com/vercel/next.js/issues/57964

**Comment by luciovilla** [comment] 2023-11-26 20:38
Same and downgrading to Next.js `v14.0.1` fixes it.

**Comment by luwes** [comment] 2023-12-01 19:48
this is fixed in the latest Next.js canary
https://github.com/vercel/next.js/releases/tag/v14.0.4-canary.33

**Comment by luwes** [comment] 2023-12-08 00:54
this is resolved in Next.js v14.0.4 https://github.com/vercel/next.js/releases/tag/v14.0.4

**Closed by luwes** 2023-12-08 00:54 UTC
