### ISSUE TITLE
pnpx next-video sync --dir /public - The "to" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by nicitaacom** [muxinc/next-video#200] opened 2024-03-10 07:54 UTC
![image](https://github.com/muxinc/next-video/assets/39565703/15d1b7ac-ccd8-4298-8941-eb660c04f152)

I tried also 

![image](https://github.com/muxinc/next-video/assets/39565703/cfac939b-61e9-42b0-8eb5-54f37fa88d72)

  "next-video": "^0.16.0",
  "next": "14.1.0",

tsconfig.json
```
  "include": ["video.d.ts", "next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
```

I want to save my videos in public folder ./public
I'm sure that I set my .env
```
MUX_TOKEN_ID='some token here'
MUX_TOKEN_SECRET='some secret here'
``

**Comment by luwes** [comment] 2024-03-10 13:40
duplicate of https://github.com/muxinc/next-video/issues/196

**Closed by luwes** 2024-03-10 13:40 UTC
