### ISSUE TITLE
Failed to load next.config.js and 'hls.js' doesn't contain a default export

### ISSUE THREAD

**Issue by Codensity30** [muxinc/next-video#117] opened 2023-12-01 15:02 UTC
When I tried to install the library or run the video sync command. I got this error in my terminal, but the further process continued.

![image](https://github.com/muxinc/next-video/assets/129579058/08cf886a-76a7-4676-b1a7-9e2e3e2d8346)

My project structure.

![image](https://github.com/muxinc/next-video/assets/129579058/c724f978-9be4-47f9-9cbc-fcacb67440a2)

I somehow edited the next.config.js file manually using docs. But you can fix it.

When I tried to run the app. I got this error - 

![image](https://github.com/muxinc/next-video/assets/129579058/3594ee49-9370-428d-92a3-1d5d8ad74320)

Which crashed the app, how can I fix it?

**Comment by heff** [comment] 2023-12-01 21:05
Thanks for the heads up! I haven't seen this before when working with brand new next.js projects. Can you tell me anymore about your project that might help? Could it be a file system permissions issue? I think we're going to update the first error to provide more details.

The hls.js error I think happens when it's loaded on the server. Can you tell me about where/how you're loading he video in a page?

**Comment by luwes** [comment] 2023-12-01 23:47
we just noticed that the hls.js error is probably the same issue than 
https://github.com/muxinc/next-video/issues/109#issuecomment-1836679432

it's caused by a Next.js bundle bug. try upgrading to the latest canary or downgrading to 14.0.1 I think.

**Comment by Codensity30** [comment] 2023-12-02 02:59
@heff I haven't modified anything regarding permissions just created the next app using the cmd mentioned in next.js docs. 
As far as video is concerned I'm just exporting a react component which returns the Video component provided by next-video. And is rendered on page.

**Comment by luwes** [comment] 2023-12-19 18:12
2nd issue is fixed in https://github.com/muxinc/next-video/issues/109#issuecomment-1846333718
it was a Next.js bug 

the 1st issue, could it be caused by you having run `npx next-video sync` not in the root folder of your next.js project?
it requires a next.config.js or next.config.mjs in the current working directory...

I'm closing but please let me know if you keep running into the 1st issue.

**Closed by luwes** 2023-12-19 18:12 UTC
