### ISSUE TITLE
Issue syncing using Vercel Blob

### ISSUE THREAD

**Issue by JosefAl1** [muxinc/next-video#119] opened 2023-12-07 09:13 UTC
When running "npx next-video sync," I get this message: 
`An unknown error occurred MuxError: The MUX_TOKEN_ID environment variable is missing or empty; either provide it, or instantiate the Mux client with a tokenId option, like new Mux({ tokenId: 'my tokenId' }).`

Even though my next.config.js is:
```
const { withNextVideo } = require('next-video/process');

/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = withNextVideo(nextConfig, {
  provider: 'vercel-blob',
});
```

Additionally, I had to downgrade from Next.js 14.0.3 to 14.0.1 for it to run. Also, when running "npx next-video init", I get this message: "Failed to load next.config.js."

**Comment by luwes** [comment] 2023-12-07 17:19
thanks for the feedback!

are you on the latest version v0.9.1?

the Next.js downgrading is related to a bug on the Next.js side. 
see here https://github.com/muxinc/next-video/issues/109#issuecomment-1836679432

**Comment by luwes** [comment] 2023-12-20 13:57
are you still seeing any issues with the latest version? 
we can't reproduce this so closing for now. let us know!

**Closed by luwes** 2023-12-20 13:57 UTC

**Comment by luwes** [comment] 2023-12-20 14:50
I just went through a setup from scratch. https://codesandbox.io/p/devbox/next-video-vercel-blob-h3n69k

could it be that the video json file in the /videos folder still has the provider set to `mux`.
it could happen if you first imported a video without having set the provider in next.config.js

change that to `vercel-blob`, set the `BLOB_READ_WRITE_TOKEN` of Vercel and then `npx next-video sync` should work
